PORTNAME=	libstatgrab
PORTVERSION=	0.92.1
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	https://github.com/libstatgrab/libstatgrab/releases/download/LIBSTATGRAB_${PORTVERSION:S/./_/}/ \
		http://ftp.mirrorservice.org/pub/i-scream/libstatgrab/ \
		http://ftp.i-scream.org/pub/i-scream/libstatgrab/

MAINTAINER=	koue@chaosophia.net
COMMENT=	Provides a useful interface to system statistics
WWW=		https://libstatgrab.org/

LICENSE=	LGPL21

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--without-perl5

.include <bsd.port.mk>
